--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.8.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14/09/2022 9:19:47 CH
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `misa.web08.gpbl.tnmanh`;

--
-- Drop procedure `Proc_employee_Filter`
--
DROP PROCEDURE IF EXISTS Proc_employee_Filter;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Drop table `positions`
--
DROP TABLE IF EXISTS positions;

--
-- Set default database
--
USE `misa.web08.gpbl.tnmanh`;

--
-- Create table `positions`
--
CREATE TABLE positions (
  PositionID char(36) NOT NULL COMMENT 'ID chức vụ',
  PositionCode varchar(20) NOT NULL COMMENT 'Mã chức vụ',
  PositionName varchar(255) NOT NULL COMMENT 'Tên chức danh',
  Description varchar(255) DEFAULT NULL COMMENT 'Giới thiệu về chức danh',
  CreatedDate datetime NOT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(100) NOT NULL COMMENT 'Tạo bởi người dùng',
  ModifiedDate datetime NOT NULL COMMENT 'Ngày chỉnh sửa gần nhất',
  ModifiedBy varchar(100) NOT NULL COMMENT 'Người chỉnh sửa gần nhất',
  PRIMARY KEY (PositionID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng chức vụ';

--
-- Create index `DepartmentCode` on table `positions`
--
ALTER TABLE positions
ADD UNIQUE INDEX DepartmentCode (PositionCode);

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentID char(36) NOT NULL COMMENT 'ID đơn vị phòng ban',
  DepartmentCode varchar(20) NOT NULL COMMENT 'Mã đơn vị phòng ban',
  DepartmentName varchar(255) NOT NULL COMMENT 'Tên đơn vị phòng ban',
  Description varchar(255) DEFAULT NULL COMMENT 'Giới thiệu về đơn vị, phòng ban',
  CreatedDate datetime NOT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(100) NOT NULL COMMENT 'Tạo bởi người dùng',
  ModifiedDate datetime NOT NULL COMMENT 'Ngày chỉnh sửa gần nhất',
  ModifiedBy varchar(100) NOT NULL COMMENT 'Người chỉnh sửa gần nhất',
  PRIMARY KEY (DepartmentID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng đơn vị phòng ban';

--
-- Create index `DepartmentCode` on table `department`
--
ALTER TABLE department
ADD UNIQUE INDEX DepartmentCode (DepartmentCode);

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(36) NOT NULL COMMENT 'Id nhân viên',
  EmployeeCode varchar(20) NOT NULL COMMENT 'Mã nhân viên',
  FullName varchar(100) NOT NULL COMMENT 'Tên nhân viên',
  DateOfBirth datetime DEFAULT NULL COMMENT 'Ngày sinh của nhân viên',
  EmployeeGender tinyint DEFAULT NULL COMMENT 'Giới tính nhân viên',
  IdentityCard varchar(25) DEFAULT NULL COMMENT 'Căn cước công dân/ chứng minh thư nhân viên',
  IdentityPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp  căn cước công dân/ chứng minh thư nhân viên',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ của nhân viên',
  PNumRelative varchar(50) DEFAULT NULL COMMENT 'Số điện thoại cá nhân',
  PNumFix varchar(50) DEFAULT NULL COMMENT 'Số điện thoại cố định',
  Email varchar(100) DEFAULT NULL COMMENT 'Địa chỉ email',
  BankAccount varchar(25) DEFAULT NULL COMMENT 'Số tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranch varchar(255) DEFAULT NULL COMMENT 'Tên chi nhánh ngân hàng',
  DepartmentID char(36) NOT NULL COMMENT 'Mã đơn vị',
  DepartmentName varchar(255) NOT NULL COMMENT 'Tên đơn vị',
  PositionID char(36) NOT NULL COMMENT 'Mã chức danh',
  PositionName varchar(255) NOT NULL COMMENT 'Tên chức danh',
  CreatedDate datetime NOT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(100) NOT NULL COMMENT 'Tạo bởi người dùng',
  ModifiedDate datetime NOT NULL COMMENT 'Ngày sửa gần đây nhất',
  ModifiedBy varchar(100) NOT NULL COMMENT 'Người sửa gần đây nhất',
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng nhân viên';

--
-- Create index `IX_Employee_FullName` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX IX_Employee_FullName (FullName);

--
-- Create index `IX_Employee_EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX IX_Employee_EmployeeCode (EmployeeCode);

--
-- Create index `EmployeeID` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX EmployeeID (EmployeeID);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_Employee_Department_DepartmentID FOREIGN KEY (DepartmentID)
REFERENCES department (DepartmentID);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_Employee_Positions_PositionID FOREIGN KEY (PositionID)
REFERENCES positions (PositionID);

DELIMITER $$

--
-- Create procedure `Proc_employee_Filter`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_employee_Filter (IN v_Offset int,
IN v_Sort int)
COMMENT '
  -- Author:        TNMANH
  -- Created date:  14/09/2022
  -- Description:   Filter ( học sau )
  -- Modified by:
  -- Code chạy thử: CALL `misa.web08.gpbl.tnmanh`.Proc_employee_Filter(0, 10, NULL, "EmployeeName like ''%Trường%''");'
BEGIN


END
$$

DELIMITER ;

-- 
-- Dumping data for table positions
--
-- Table `misa.web08.gpbl.tnmanh`.positions does not contain any data (it is empty)

-- 
-- Dumping data for table department
--
-- Table `misa.web08.gpbl.tnmanh`.department does not contain any data (it is empty)

-- 
-- Dumping data for table employee
--
-- Table `misa.web08.gpbl.tnmanh`.employee does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;